defmodule BotArmyBriefingBot.BriefingBuilder do
  @moduledoc """
  Builds markdown briefing content from GTD tasks, fitness plans, and health snapshots.
  """
  @morning_videos [
    %{
      title: "Can't Hurt Me — David Goggins",
      url: "https://youtube.com/watch?v=5tSTk1083VY"
    },
    %{
      title: "The Obstacle Is The Way — Ryan Holiday",
      url: "https://youtube.com/watch?v=MMMrYaQHBLo"
    },
    %{
      title: "Why We Sleep — Matthew Walker TED",
      url: "https://youtube.com/watch?v=5MuIMqhT8oM"
    },
    %{
      title: "Atomic Habits — James Clear",
      url: "https://youtube.com/watch?v=YT7tQzmGRLA"
    },
    %{
      title: "Start With Why — Simon Sinek TED",
      url: "https://youtube.com/watch?v=u4ZoJKF_VuA"
    },
    %{
      title: "Flow State — Steven Kotler",
      url: "https://youtube.com/watch?v=XG_hNZ5T4nY"
    },
    %{
      title: "Inside the Mind of a Master Procrastinator — TED",
      url: "https://youtube.com/watch?v=arj7oStGLkU"
    }
  ]

  def build(data) do
    date_str = data[:date] || Date.to_string(Date.utc_today())
    weather = data[:weather] || %{}
    gtd_tasks = data[:gtd_tasks] || []
    fitness_plan = data[:fitness_plan] || %{}
    health_snapshot = data[:health_snapshot] || %{}
    time_str = DateTime.utc_now() |> DateTime.to_iso8601()

    video = pick_video()
    gtd_section = format_gtd_section(gtd_tasks)
    weather_section = format_weather_section(weather)
    fitness_section = format_fitness_section(fitness_plan)
    health_section = format_health_section(health_snapshot)

    """
    # Morning Briefing — #{date_str}

    #{weather_section}

    #{fitness_section}

    #{gtd_section}

    #{health_section}

    ## 🎬 Morning Fuel
    [#{video.title}](#{video.url})

    ---
    *Generated by Bot Army at #{time_str} UTC*
    """
  end

  defp format_gtd_section(tasks) do
    task_list =
      tasks
      |> Enum.take(5)
      |> Enum.map_join("\n", fn task ->
        reason = task["why_next_reason"] || "Next up"
        "- **#{task["title"]}** — #{reason}"
      end)

    """
    ## ✅ Your Priorities (Top 5)
    #{task_list}
    """
  end

  defp format_weather_section(weather) do
    case weather do
      %{"condition" => condition, "temp" => temp, "city" => city} ->
        """
        ## 🌤 Weather
        #{String.capitalize(condition)}, #{temp}°F in #{city}
        """

      _ ->
        "## 🌤 Weather\nNo weather data available"
    end
  end

  defp format_fitness_section(plan) do
    case plan do
      %{"type" => type, "estimated_minutes" => minutes} ->
        """
        ## 💪 Today's Workout
        **#{String.capitalize(type)}** · #{minutes} min

        [View full plan in PARA](obsidian://vault/PARA/resources/fitness/plans)
        """

      _ ->
        "## 💪 Today's Workout\nNo plan generated yet"
    end
  end

  defp format_health_section(snapshot) do
    case snapshot do
      %{"summary" => summary} ->
        "## 🏥 System Health\n#{summary}"

      %{"suggested_focus" => focus} ->
        "## 🏥 System Health\nFocus: #{focus}"

      _ ->
        "## 🏥 System Health\nAll systems nominal"
    end
  end

  defp pick_video do
    index = Date.utc_today() |> Date.day_of_year() |> rem(length(@morning_videos))
    Enum.at(@morning_videos, index)
  end
end
