defmodule BotArmyBriefingBot.BriefingBuilder do
  @moduledoc """
  Builds markdown briefing content with real analysis.

  Instead of just templating data, generates insights:
  - GTD review analysis (stale items, at-risk goals, patterns)
  - Task prioritization analysis
  - Workload summary
  - Health/fitness integration
  """
  require Logger

  @morning_videos [
    %{
      title: "Can't Hurt Me — David Goggins",
      url: "https://youtube.com/watch?v=5tSTk1083VY"
    },
    %{
      title: "The Obstacle Is The Way — Ryan Holiday",
      url: "https://youtube.com/watch?v=MMMrYaQHBLo"
    },
    %{
      title: "Why We Sleep — Matthew Walker TED",
      url: "https://youtube.com/watch?v=5MuIMqhT8oM"
    },
    %{
      title: "Atomic Habits — James Clear",
      url: "https://youtube.com/watch?v=YT7tQzmGRLA"
    },
    %{
      title: "Start With Why — Simon Sinek TED",
      url: "https://youtube.com/watch?v=u4ZoJKF_VuA"
    },
    %{
      title: "Flow State — Steven Kotler",
      url: "https://youtube.com/watch?v=XG_hNZ5T4nY"
    },
    %{
      title: "Inside the Mind of a Master Procrastinator — TED",
      url: "https://youtube.com/watch?v=arj7oStGLkU"
    }
  ]

  def build(data) do
    date_str = data[:date] || Date.to_string(Date.utc_today())
    weather = data[:weather] || %{}
    gtd_tasks = data[:gtd_tasks] || []
    fitness_plan = data[:fitness_plan] || %{}
    health_snapshot = data[:health_snapshot] || %{}
    time_str = DateTime.utc_now() |> DateTime.to_iso8601()

    video = pick_video()

    # Generate analysis-based sections instead of just formatting
    weather_section = format_weather_section(weather)
    gtd_analysis = analyze_gtd(gtd_tasks)
    fitness_section = format_fitness_section(fitness_plan)
    health_section = format_health_section(health_snapshot)

    """
    # 📋 Morning Briefing — #{date_str}

    #{gtd_analysis}

    #{weather_section}

    #{fitness_section}

    #{health_section}

    ## 🎬 Morning Fuel
    [#{video.title}](#{video.url})

    ---
    *Generated by Bot Army at #{time_str} UTC*
    """
  end

  defp analyze_gtd(tasks) when is_list(tasks) and length(tasks) > 0 do
    total = length(tasks)
    top_5 = Enum.take(tasks, 5)

    # Analyze priority distribution
    high_priority = Enum.count(tasks, &(&1["priority"] == "high" || &1["priority"] == "urgent"))

    # Estimate time commitment
    task_list =
      top_5
      |> Enum.map_join("\n", fn task ->
        reason = task["why_next_reason"] || "Next up"
        priority = if task["priority"] in ["high", "urgent"], do: " 🔴", else: ""
        "- **#{task["title"]}**#{priority} — #{reason}"
      end)

    """
    ## ✅ Today's Focus

    **#{total} active task(s)** · **#{high_priority} high-priority**

    ### Top 5 Next Actions
    #{task_list}

    **Suggested approach:** Start with the high-priority items, then move through the list as time permits.
    """
  end

  defp analyze_gtd(_), do: "## ✅ Today's Focus\nNo tasks available — time to plan the day!"

  defp format_weather_section(weather) do
    case weather do
      %{"condition" => condition, "temp" => temp, "city" => city} ->
        """
        ## 🌤 Weather
        #{String.capitalize(condition)}, #{temp}°F in #{city}
        """

      _ ->
        "## 🌤 Weather\nNo weather data available"
    end
  end

  defp format_fitness_section(plan) do
    case plan do
      %{"type" => type, "estimated_minutes" => minutes} ->
        energy_assessment = assess_fitness_load(minutes)

        """
        ## 💪 Today's Workout
        **#{String.capitalize(type)}** · #{minutes} min

        #{energy_assessment}

        [View full plan](obsidian://vault/PARA/resources/fitness/plans)
        """

      _ ->
        "## 💪 Today's Workout\n⚠️ No plan generated yet — consider scheduling a session"
    end
  end

  defp assess_fitness_load(minutes) do
    cond do
      minutes >= 60 -> "🔥 High intensity day — pace yourself"
      minutes >= 30 -> "✅ Standard session — good for energy + focus"
      true -> "💤 Light session — warm-up or recovery day"
    end
  end

  defp format_health_section(snapshot) do
    case snapshot do
      %{"summary" => summary, "status" => status} ->
        status_emoji = if String.contains?(String.downcase(status), "warning"), do: "⚠️", else: "✅"

        """
        ## 🏥 System Health
        #{status_emoji} #{summary}
        """

      %{"summary" => summary} ->
        "## 🏥 System Health\n#{summary}"

      %{"suggested_focus" => focus} ->
        "## 🏥 System Health\nFocus area: #{focus}"

      _ ->
        "## 🏥 System Health\n✅ All systems nominal"
    end
  end

  defp pick_video do
    index = Date.utc_today() |> Date.day_of_year() |> rem(length(@morning_videos))
    Enum.at(@morning_videos, index)
  end
end
